# Generated by Django 4.2 on 2023-05-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('full_text', models.TextField(verbose_name='Полный текст')),
                ('data_of_publish', models.DateTimeField(verbose_name='Дата и время публикации')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
            ],
        ),
    ]
