# Generated by Django 4.2 on 2023-05-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('otchestvo', models.CharField(default='', max_length=50, verbose_name='Отчество')),
                ('teams_name', models.CharField(max_length=50, verbose_name='Название команды')),
                ('login', models.CharField(default='', max_length=50, verbose_name='Логин')),
                ('password', models.CharField(default='', max_length=50, verbose_name='Пароль')),
                ('email', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('doc_number', models.CharField(default='', max_length=50, verbose_name='Номер договора')),
            ],
        ),
    ]
